/**
 * Real-time SDF sphere-tracer for the 3D Viewport live preview (3D-2).
 *
 * Renders the same signed distance field as the CPU/GPU polygonizers but
 * via a fragment-shader raymarcher — no geometry, no mesh, instant display.
 * Shows while the user is typing or while generation is in progress, then
 * disappears once the real polygonized mesh is available.
 *
 * Architecture:
 *   - A PlaneGeometry(2,2) fills NDC space; its vertex shader bypasses the
 *     Three.js camera transform (gl_Position = vec4(pos.xy,1,1)).
 *   - The fragment shader reconstructs world-space rays from the Three.js
 *     camera uniforms (position, world matrix, inverse-projection matrix).
 *   - The SDF is inlined at build time by compileSdfGLSL() so the browser
 *     never re-links the shader program between frames; only the camera
 *     uniforms change.
 *   - Sphere-tracing: 96 steps, early-out at d < 0.0005, max depth 5.0.
 *   - Lighting: one-shot PBR-ish approximation (diffuse + specular + AO + rim).
 *   - Normals: central-difference finite differences (h = 0.001).
 */

import { useRef, useMemo, useEffect } from 'react';
import { useThree, useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { compileSdfGLSL, type CompiledGLSL } from '../lib/sdf-glsl';
import type { ShapeProgram } from '../lib/sdf-compiler';

// ── shader sources ───────────────────────────────────────────────────────────

const VERT = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  // Bypass all camera/model transforms — cover NDC space directly.
  // PlaneGeometry(2,2) has positions in [-1,1], so this is correct.
  gl_Position = vec4(position.xy, 1.0, 1.0);
}
`;

function buildFrag(compiled: CompiledGLSL): string {
  const { glsl, metalness, roughness } = compiled;
  return /* glsl */ `
precision highp float;

varying vec2 vUv;

uniform vec3  uCamPos;
uniform mat4  uCamWorld;
uniform mat4  uInvProj;
uniform float uMetalness;
uniform float uRoughness;
uniform float uTime;

// ── inlined SDF (generated by compileSdfGLSL) ────────────────────────────────
${glsl}
// ────────────────────────────────────────────────────────────────────────────

// Finite-difference normal (matches the CPU/GPU polygonizers' gradient h).
vec3 calcNormal(vec3 p) {
  const float h = 0.001;
  return normalize(vec3(
    sdf(p + vec3(h,0,0)) - sdf(p - vec3(h,0,0)),
    sdf(p + vec3(0,h,0)) - sdf(p - vec3(0,h,0)),
    sdf(p + vec3(0,0,h)) - sdf(p - vec3(0,0,h))
  ));
}

// Soft shadow — cheap version for directional light.
float shadow(vec3 ro, vec3 rd, float k) {
  float res = 1.0, t = 0.02;
  for (int i = 0; i < 32; i++) {
    float d = sdf(ro + t * rd);
    if (d < 0.0002) return 0.0;
    res = min(res, k * d / t);
    t += clamp(d, 0.005, 0.3);
    if (t > 2.0) break;
  }
  return clamp(res, 0.0, 1.0);
}

// Ambient occlusion via SDF sampling along the normal.
float ao(vec3 p, vec3 n) {
  float occ = 0.0, wt = 1.0;
  for (int i = 1; i <= 5; i++) {
    float s = float(i) * 0.06;
    float d = sdf(p + n * s);
    occ += wt * (s - d);
    wt  *= 0.75;
  }
  return clamp(1.0 - 1.8 * occ, 0.0, 1.0);
}

// Reconstruct world-space ray direction from UV and camera matrices.
vec3 getRayDir(vec2 uv) {
  vec4 clip = vec4(uv * 2.0 - 1.0, -1.0, 1.0);
  vec4 view = uInvProj * clip;
  view = vec4(view.xy, -1.0, 0.0);
  return normalize((uCamWorld * view).xyz);
}

void main() {
  vec3 ro = uCamPos;
  vec3 rd = getRayDir(vUv);

  // Sphere-trace. The default orbit camera sits ~7 units out, so the march
  // budget must comfortably exceed that (a 5.0 cap made EVERY ray miss —
  // the preview rendered nothing while reporting no errors). Models live in
  // [-1.2,1.2]³, so skip ahead to just outside that bound before stepping.
  float t = max(0.0, length(ro) - 2.5);
  bool hit = false;
  for (int i = 0; i < 96; i++) {
    float d = sdf(ro + t * rd);
    if (d < 0.0005) { hit = true; break; }
    t += d;
    if (t > 20.0) break;
  }

  // Miss → discard so the scene (grid, shadows) shows through; the preview
  // only owns the pixels the model actually covers.
  if (!hit) discard;

  vec3 pos  = ro + t * rd;
  vec3 nor  = calcNormal(pos);
  vec3 col  = sdfColor(pos);

  // Lights (match the three.js scene: spot at (10,10,10), point at (-10,-10,-10))
  vec3 lig1 = normalize(vec3(10.0, 10.0, 10.0));
  vec3 lig2 = normalize(vec3(-10.0,-10.0,-10.0));

  // PBR-ish: diffuse + specular + ambient
  float m    = clamp(uMetalness, 0.0, 1.0);
  float rgh  = clamp(uRoughness, 0.05, 1.0);
  float rgh2 = rgh * rgh;

  float ndl1 = max(dot(nor, lig1), 0.0);
  float ndl2 = max(dot(nor, lig2), 0.0) * 0.35;

  vec3  hal1 = normalize(lig1 - rd);
  float spec1 = pow(max(dot(nor, hal1), 0.0), 2.0 / rgh2) * (1.0 - rgh) * 0.8;

  // Soft shadow from the main spot
  float sha  = shadow(pos + nor * 0.002, lig1, 16.0);
  float occ  = ao(pos, nor);

  // Rim light
  float rim  = pow(1.0 - max(dot(nor, -rd), 0.0), 3.0) * 0.25;

  // Base colour: mix between diffuse-tinted and white for metalness
  vec3 diffCol  = col * mix(vec3(1.0), vec3(0.04), m);
  vec3 specCol  = mix(vec3(1.0), col, m);

  vec3 ambient  = col * 0.08 * occ;
  vec3 diffuse  = diffCol * (ndl1 * sha + ndl2) * occ;
  vec3 specular = specCol * spec1 * sha;
  vec3 rimCol   = vec3(0.4, 0.55, 1.0) * rim * occ;

  vec3 finalCol = ambient + diffuse + specular + rimCol;

  // Subtle fog to match the scene depth feel
  float fog = 1.0 - exp(-t * 0.15);
  finalCol  = mix(finalCol, vec3(0.059, 0.090, 0.161), fog * 0.4);

  gl_FragColor = vec4(finalCol, 1.0);
}
`;
}

// ── component ─────────────────────────────────────────────────────────────────

export interface SDFRaytracerProps {
  program: ShapeProgram;
}

/**
 * Drop this inside a `<Canvas>` to show a live sphere-traced preview of the
 * given ShapeProgram.  The shader is (re-)compiled whenever `program` changes.
 * Camera uniforms are updated every frame via useFrame.
 */
export function SDFRaytracer({ program }: SDFRaytracerProps) {
  const { camera } = useThree();
  const matRef = useRef<THREE.ShaderMaterial>(null);

  // Build the fragment shader once per program identity.
  const { vertSrc, fragSrc, metalness, roughness } = useMemo(() => {
    const compiled = compileSdfGLSL(program);
    return {
      vertSrc: VERT,
      fragSrc: buildFrag(compiled),
      metalness: compiled.metalness,
      roughness: compiled.roughness,
    };
  }, [program]);

  // Initial uniforms — values are updated every frame in useFrame.
  const uniforms = useMemo(
    () => ({
      uCamPos:    { value: new THREE.Vector3() },
      uCamWorld:  { value: new THREE.Matrix4() },
      uInvProj:   { value: new THREE.Matrix4() },
      uMetalness: { value: metalness },
      uRoughness: { value: roughness },
      uTime:      { value: 0 },
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [vertSrc, fragSrc], // rebuild when shader changes, not when metalness/roughness vary
  );

  // Keep metalness / roughness in sync without a full shader rebuild.
  useEffect(() => {
    if (!matRef.current) return;
    matRef.current.uniforms.uMetalness.value = metalness;
    matRef.current.uniforms.uRoughness.value = roughness;
  }, [metalness, roughness]);

  useFrame(({ clock }) => {
    const mat = matRef.current;
    if (!mat) return;
    camera.updateMatrixWorld();
    mat.uniforms.uCamPos.value.setFromMatrixPosition(camera.matrixWorld);
    mat.uniforms.uCamWorld.value.copy(camera.matrixWorld);
    // PerspectiveCamera exposes projectionMatrixInverse directly.
    const pCam = camera as THREE.PerspectiveCamera;
    if (pCam.projectionMatrixInverse) {
      mat.uniforms.uInvProj.value.copy(pCam.projectionMatrixInverse);
    }
    mat.uniforms.uTime.value = clock.getElapsedTime();
  });

  return (
    // renderOrder 1: draw AFTER the grid/shadows so the traced model paints
    // over them (at -1 the grid was drawn on top of the preview). Culling off:
    // the plane's bounds are meaningless — the vertex shader ignores every
    // transform, so three must never frustum-cull it away.
    <mesh renderOrder={1} frustumCulled={false}>
      {/* PlaneGeometry(2,2) has vertex positions in [-1,1] — the vertex shader
          uses them directly as NDC coordinates, bypassing the camera. */}
      <planeGeometry args={[2, 2]} />
      <shaderMaterial
        ref={matRef}
        key={fragSrc} // force shader recompile on program change
        vertexShader={vertSrc}
        fragmentShader={fragSrc}
        uniforms={uniforms}
        depthTest={false}
        depthWrite={false}
      />
    </mesh>
  );
}
